from .templates import (
    CLASSIFICATION_SYSTEM_PROMPT,
    REASONING_SYSTEM_PROMPT,
    SUGGESTION_SYSTEM_PROMPT,
)

__all__ = ["REASONING_SYSTEM_PROMPT", "CLASSIFICATION_SYSTEM_PROMPT", "SUGGESTION_SYSTEM_PROMPT"]
